from dataclasses import dataclass

@dataclass
class GOESProduct:
    satellite:str
    sensor:str
    level:str
    scan:str

    def __str__(self):
        return "-".join([
            self.satellite,
            self.sensor,
            self.level,
            self.scan,
            ])

bands = {
    1:{
        "ctr_wl":0.47,
        "name":"Visible Blue",
        "default_res":1,
        "kappa0":0.0015839,
        },
    2:{
        "ctr_wl":0.64,
        "name":"Visible Red 0",
        "default_res":.5,
        "kappa0":0.0019586,
        },
    3:{
        "ctr_wl":0.86,
        "name":"Near-Infrared Veggie",
        "default_res":1,
        "kappa0":0.0033384,
        },
    4:{
        "ctr_wl":1.37,
        "name":"Near-Infrared Cirrus",
        "default_res":2,
        "kappa0":0.008853,
        },
    5:{
        "ctr_wl":1.6,
        "name":"Near-Infrared Snow/Ice",
        "default_res":1,
        "kappa0":0.0131734,
        },
    6:{
        "ctr_wl":2.2,
        "name":"Near-Infrared Cloud particle size",
        "default_res":2,
        "kappa0":0.0415484,
        },
    7:{
        "ctr_wl":3.9,
        "name":"Infrared Shortwave window",
        "default_res":2,
        },
    8:{
        "ctr_wl":6.2,
        "name":"Infrared Upper-level water vapor",
        "default_res":2,
        },
    9:{
        "ctr_wl":6.9,
        "name":"Infrared Midlevel water vapor",
        "default_res":2,
        },
    10:{
        "ctr_wl":7.3,
        "name":"Infrared Lower-level water vapor",
        "default_res":2,
        },
    11:{
        "ctr_wl":8.4,
        "name":"Infrared Cloud-top phase",
        "default_res":2,
        },
    12:{
        "ctr_wl":9.6,
        "name":"Infrared Ozone",
        "default_res":2,
        },
    13:{
        "ctr_wl":10.3,
        "name":"Infrared 'Clean' longwave window",
        "default_res":2,
        },
    14:{
        "ctr_wl":11.2,
        "name":"Infrared Longwave window",
        "default_res":2,
        },
    15:{
        "ctr_wl":12.3,
        "name":"Infrared 'Dirty' longwave window",
        "default_res":2,
        },
    16:{
        "ctr_wl":13.3,
        "name":"Infrared CO2 longwave",
        "default_res":2,
        },
    }

valid_goes_products = [
    GOESProduct(satellite="16", sensor="ABI", level="L1b", scan="RadC"),
    GOESProduct(satellite="16", sensor="ABI", level="L1b", scan="RadF"),
    GOESProduct(satellite="16", sensor="ABI", level="L1b", scan="RadM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHA2KMC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHA2KMF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHA2KMM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHAC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHAF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHAM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHP2KMC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHP2KMF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHP2KMM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHTF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACHTM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACMC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACMF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACMM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACTPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACTPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ACTPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ADPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ADPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="ADPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="AICEF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="AITAF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="AODC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="AODF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="BRFC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="BRFF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="BRFM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CCLC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CCLF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CCLM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CMIPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CMIPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CMIPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="COD2KMF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CODC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CODF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CPSC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CPSF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CPSM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CTPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="CTPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWVC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWVF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DMWVM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSIC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSIF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSIM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSRC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSRF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="DSRM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FDCC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FDCF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FDCM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FSCC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FSCF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="FSCM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSAC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSAF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSAM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LST2KMF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSTC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSTF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LSTM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVMPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVMPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVMPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVTPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVTPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="LVTPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="MCMIPC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="MCMIPF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="MCMIPM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="RRQPEF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="RSRC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="RSRF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="SSTF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="TPWC"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="TPWF"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="TPWM"),
    GOESProduct(satellite="16", sensor="ABI", level="L2", scan="VAAF"),
    GOESProduct(satellite="16", sensor="EXIS", level="L1b", scan="SFEU"),
    GOESProduct(satellite="16", sensor="EXIS", level="L1b", scan="SFXR"),
    GOESProduct(satellite="16", sensor="GLM", level="L2", scan="LCFA"),
    GOESProduct(satellite="16", sensor="MAG", level="L1b", scan="GEOF"),
    GOESProduct(satellite="16", sensor="SEIS", level="L1b", scan="EHIS"),
    GOESProduct(satellite="16", sensor="SEIS", level="L1b", scan="MPSH"),
    GOESProduct(satellite="16", sensor="SEIS", level="L1b", scan="MPSL"),
    GOESProduct(satellite="16", sensor="SEIS", level="L1b", scan="SGPS"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="Fe093"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="Fe131"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="Fe171"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="Fe195"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="Fe284"),
    GOESProduct(satellite="16", sensor="SUVI", level="L1b", scan="He303"),
    GOESProduct(satellite="17", sensor="ABI", level="L1b", scan="RadC"),
    GOESProduct(satellite="17", sensor="ABI", level="L1b", scan="RadF"),
    GOESProduct(satellite="17", sensor="ABI", level="L1b", scan="RadM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACHAC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACHAF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACHAM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACHTF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACHTM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACMC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACMF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACMM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACTPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACTPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ACTPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ADPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ADPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="ADPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="AICEF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="AITAF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="AODC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="AODF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="BRFC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="BRFF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="BRFM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CMIPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CMIPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CMIPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CODC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CODF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CPSC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CPSF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CPSM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CTPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="CTPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWVC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWVF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DMWVM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSIC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSIF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSIM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSRC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSRF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="DSRM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="FDCC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="FDCF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="FDCM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSAC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSAF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSAM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LST2KMF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSTC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSTF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LSTM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVMPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVMPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVMPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVTPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVTPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="LVTPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="MCMIPC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="MCMIPF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="MCMIPM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="RRQPEF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="RSRC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="RSRF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="SSTF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="TPWC"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="TPWF"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="TPWM"),
    GOESProduct(satellite="17", sensor="ABI", level="L2", scan="VAAF"),
    GOESProduct(satellite="17", sensor="EXIS", level="L1b", scan="SFEU"),
    GOESProduct(satellite="17", sensor="EXIS", level="L1b", scan="SFXR"),
    GOESProduct(satellite="17", sensor="GLM", level="L2", scan="LCFA"),
    GOESProduct(satellite="17", sensor="MAG", level="L1b", scan="GEOF"),
    GOESProduct(satellite="17", sensor="SEIS", level="L1b", scan="EHIS"),
    GOESProduct(satellite="17", sensor="SEIS", level="L1b", scan="MPSH"),
    GOESProduct(satellite="17", sensor="SEIS", level="L1b", scan="MPSL"),
    GOESProduct(satellite="17", sensor="SEIS", level="L1b", scan="SGPS"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="Fe093"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="Fe131"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="Fe171"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="Fe195"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="Fe284"),
    GOESProduct(satellite="17", sensor="SUVI", level="L1b", scan="He303"),
    GOESProduct(satellite="19", sensor="ABI", level="Flood", scan="Day"),
    GOESProduct(satellite="19", sensor="ABI", level="Flood", scan="Hourly"),
    GOESProduct(satellite="19", sensor="ABI", level="L1b", scan="RadC"),
    GOESProduct(satellite="19", sensor="ABI", level="L1b", scan="RadF"),
    GOESProduct(satellite="19", sensor="ABI", level="L1b", scan="RadM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHA2KMC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHA2KMF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHA2KMM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHAC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHAF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHAM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHP2KMC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHP2KMF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHP2KMM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHTF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACHTM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACMC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACMF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACMM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACTPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACTPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ACTPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ADPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ADPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="ADPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="AICEF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="AITAF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="AODC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="AODF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="BRFC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="BRFF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="BRFM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CCLC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CCLF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CCLM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CMIPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CMIPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CMIPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="COD2KMF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CODC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CODF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CPSC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CPSF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CPSM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CTPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="CTPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWVC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWVF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DMWVM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DSIC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DSIF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DSIM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="DSRF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FDCC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FDCF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FDCM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FSCC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FSCF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="FSCM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSAC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSAF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSAM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LST2KMF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSTC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSTF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LSTM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVMPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVMPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVMPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVTPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVTPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="LVTPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="MCMIPC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="MCMIPF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="MCMIPM"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="PARF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="RRQPEF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="RSRF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="SSTF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="TPWC"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="TPWF"),
    GOESProduct(satellite="19", sensor="ABI", level="L2", scan="TPWM"),
    GOESProduct(satellite="19", sensor="EXIS", level="L1b", scan="SFEU"),
    GOESProduct(satellite="19", sensor="EXIS", level="L1b", scan="SFXR"),
    GOESProduct(satellite="19", sensor="GLM", level="L2", scan="LCFA"),
    GOESProduct(satellite="19", sensor="MAG", level="L1b", scan="GEOF"),
    GOESProduct(satellite="19", sensor="SEIS", level="L1b", scan="EHIS"),
    GOESProduct(satellite="19", sensor="SEIS", level="L1b", scan="MPSH"),
    GOESProduct(satellite="19", sensor="SEIS", level="L1b", scan="MPSL"),
    GOESProduct(satellite="19", sensor="SEIS", level="L1b", scan="SGPS"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="Fe093"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="Fe131"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="Fe171"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="Fe195"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="Fe284"),
    GOESProduct(satellite="19", sensor="SUVI", level="L1b", scan="He303"),
    GOESProduct(satellite="18", sensor="ABI", level="Flood", scan="Day"),
    GOESProduct(satellite="18", sensor="ABI", level="Flood", scan="Hourly"),
    GOESProduct(satellite="18", sensor="ABI", level="L1b", scan="RadC"),
    GOESProduct(satellite="18", sensor="ABI", level="L1b", scan="RadF"),
    GOESProduct(satellite="18", sensor="ABI", level="L1b", scan="RadM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHA2KMC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHA2KMF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHA2KMM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHAC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHAF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHAM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHP2KMC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHP2KMF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHP2KMM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHTF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACHTM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACMC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACMF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACMM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACTPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACTPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ACTPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ADPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ADPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="ADPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="AICEF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="AITAF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="AODC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="AODF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="BRFC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="BRFF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="BRFM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CCLC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CCLF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CCLM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CMIPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CMIPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CMIPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="COD2KMF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CODC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CODF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CPSC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CPSF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CPSM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CTPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="CTPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWVC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWVF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DMWVM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSIC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSIF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSIM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSRC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSRF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="DSRM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FDCC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FDCF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FDCM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FSCC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FSCF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="FSCM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSAC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSAF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSAM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LST2KMF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSTC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSTF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LSTM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVMPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVMPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVMPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVTPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVTPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="LVTPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="MCMIPC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="MCMIPF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="MCMIPM"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="PARF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="RRQPEF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="RSRC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="RSRF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="SSTF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="TPWC"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="TPWF"),
    GOESProduct(satellite="18", sensor="ABI", level="L2", scan="TPWM"),
    GOESProduct(satellite="18", sensor="EXIS", level="L1b", scan="SFEU"),
    GOESProduct(satellite="18", sensor="EXIS", level="L1b", scan="SFXR"),
    GOESProduct(satellite="18", sensor="GLM", level="L2", scan="LCFA"),
    GOESProduct(satellite="18", sensor="MAG", level="L1b", scan="GEOF"),
    GOESProduct(satellite="18", sensor="SEIS", level="L1b", scan="EHIS"),
    GOESProduct(satellite="18", sensor="SEIS", level="L1b", scan="MPSH"),
    GOESProduct(satellite="18", sensor="SEIS", level="L1b", scan="MPSL"),
    GOESProduct(satellite="18", sensor="SEIS", level="L1b", scan="SGPS"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="Fe093"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="Fe131"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="Fe171"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="Fe195"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="Fe284"),
    GOESProduct(satellite="18", sensor="SUVI", level="L1b", scan="He303")
    ]
